plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
    id 'maven-publish'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}
apply plugin: 'net.minecraftforge.gradle'

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

mixin {
    add sourceSets.main, "pathtodivinity.refmap.json"
    config "pathtodivinity.mixins.json"
    debug.export = true
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {

    mappings channel: mapping_channel, version: mapping_version

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }
    maven {
        name = "SmartBrainLib (SBL) Maven Repo"
        url = "https://dl.cloudsmith.io/public/tslat/sbl/maven/"
    }
    maven {
        url = "https://jitpack.io"
    }
    maven {
        url = "https://cursemaven.com"
    }
    // Add 100 Media repository for Capability Syncer
    maven {
        name = '100Media'
        url = 'https://maven.100media.dev/'
    }
}

// Configure shading for Capability Syncer
configurations {
    shade
    implementation.extendsFrom shade
}

dependencies {
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.4.1")) {
        jarJar.ranged(it, "[0.4.1,)")
    }

    shade fg.deobf("dev._100media.capabilitysyncer:capabilitysyncer:1.20.1-4.0.1")

    //Pehkui
    implementation fg.deobf("com.github.Virtuoel:Pehkui:${pehkui_version}")
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    //Gecko Lib
    implementation fg.deobf("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
    //Brain Lib
    implementation fg.deobf("net.tslat.smartbrainlib:SmartBrainLib-forge-${project.minecraft_version}:${project.sbl_version}")
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    //LOTMC
    implementation fg.deobf("curse.maven:lord-of-the-mysteries-craft-1095869:7192959")
    //Legendary Monsters
    implementation fg.deobf("curse.maven:legendarymonsters-944035:6776766")
    //Wither Reincarnated
    implementation fg.deobf("curse.maven:witherreincarnated-1309246:6835382")
    //Arphex
    implementation fg.deobf("curse.maven:arphex-967672:7108032")
    //Terramity
    implementation fg.deobf("curse.maven:terramity-1084134:6054971")
    //Mutant Monsters
    implementation fg.deobf("curse.maven:mutantmonsters-852665:5107399")
    //Macabre
    implementation fg.deobf("curse.maven:macabre-933001:6442644")
    //Marium's Soulslike Weaponry
    implementation fg.deobf("curse.maven:soulsweapons-632066:6509913")
    //Cataclysm
    implementation fg.deobf("curse.maven:cataclysm-551586:6906993")
    //Mowzie's Mobs
    implementation fg.deobf("curse.maven:mowziesmobs-250498:6586086")
    //Aquamirae
    implementation fg.deobf("curse.maven:aquamirae-536254:7039863")
    //Born in Chaos
    implementation fg.deobf("curse.maven:borninchaos-686437:6833957")
    //EEEAB's Mobs
    implementation fg.deobf("curse.maven:eeeabmobs-921600:6095880")
    //Curios API
    implementation fg.deobf("curse.maven:curiosapi-309927:6418456")
    //Better Combat
    implementation fg.deobf("curse.maven:bettercombat-639842:5625757")
    //Obscure API
    implementation fg.deobf("curse.maven:obscureapi-638417:7171906")
    //Lionfish API
    implementation fg.deobf("curse.maven:lionfishapi-1001614:5922047")
    //AttributeFix
    implementation fg.deobf("curse.maven:attributefix-280510:4911084")
    //PuzzlesLib
    implementation fg.deobf("curse.maven:puzzleslib-495476:6387081")
    //Patchouli
    implementation fg.deobf("curse.maven:patchouli-306770:6164575")
    //Caelus API
    implementation fg.deobf("curse.maven:caelusapi-308989:5281700")
    //Cloth Config
    implementation fg.deobf("curse.maven:clothconfig-348521:5729105")
    //Citadel
    implementation fg.deobf("curse.maven:citadel-331936:6702068")
    //Projectile Damage
    implementation fg.deobf("curse.maven:projectiledamage-643780:4597791")
    //Player Animator
    implementation fg.deobf("curse.maven:bettercombat-658587:4587214")
    //Terrablender
    implementation fg.deobf("curse.maven:terrablender-563928:6290448")
    //Celestisynth
    implementation fg.deobf("curse.maven:celestisynth-872712:6900952")
    //Bosses of Mass Destruction
    implementation fg.deobf("curse.maven:bomd-438365:4993305")
    //Awakened Bosses
    implementation fg.deobf("curse.maven:awakenedbosses-548167:5057212")
    //Deeper Darker
    implementation fg.deobf("curse.maven:deeperdarker-659011:5906086")
    //Aether
    implementation fg.deobf("curse.maven:aether-255308:6134920")
    //Zoniex
    implementation fg.deobf("curse.maven:zoniex-1171163:6276844")
    //Jade
    implementation fg.deobf("curse.maven:jade-324717:6855440")
    //JEI
    implementation fg.deobf("curse.maven:JEI-238222:6600311")
    //JER
    implementation fg.deobf("curse.maven:JER-240630:5057220")
    //Dreamcat LIB
    implementation fg.deobf("curse.maven:dreamcast-1323703:6869654")
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

// Configure jar task for shading
tasks.named('jar', Jar).configure {
    archiveClassifier = 'slim'  // Important for shading
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    finalizedBy 'reobfJar'
}

// Configure Shadow plugin for shading Capability Syncer
shadowJar {
    archiveClassifier = ''
    configurations = [project.configurations.shade]
    relocate 'dev._100media.capabilitysyncer', "${project.group}.relocated.capabilitysyncer"
    finalizedBy 'reobfShadowJar'
}

assemble.dependsOn shadowJar

reobf {
    shadowJar {}
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url = "https://jitpack.io"
        }
        maven {
            url = "https://cursemaven.com"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}